name: Conditional

#https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Deploy to ?
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.action }}
    steps:
      - name: Setup SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: "curl ifconfig.me"

      - name: Production Only
        if: ${{ inputs.action == 'production' }}
        run: |
          echo "Ini hanya dieksekusi ketika di production saja"
