name: Conditional v2

#https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: Deploy to ?
        options:
          - staging
          - production

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.action }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build
        run: |
          npm install
          NAME="john doe" STAGE=${{ inputs.action }} node index.js

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ inputs.action }}
    steps:
      - name: Setup SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.SSH_HOSTs }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: "curl ifconfig.me"

      - name: Production Only
        if: ${{ inputs.action == 'production' }}
        run: |
          echo "Ini hanya dieksekusi ketika di production saja"

  notif:
    runs-on: ubuntu-latest
    needs: [build, deploy]
    if: always()
    environment: ${{ inputs.action }}
    steps:
      - name: Notif
        run: |
          echo "Ini akan dieksekusi menunggu job build dan deploy selesai, dan job ini akan dieksekusi meskipun ada salah satu job yg gagal"
